[tool.poetry]
authors = ["Silero Team"]
readme = "README.md"
repository = "https://github.com/snakers4/silero-models"


[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
